DROP SCHEMA IF EXISTS Todolist;
CREATE SCHEMA Todolist;

CREATE TABLE Todolist.Tasks (
  id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  title TEXT NOT NULL,
  details TEXT NOT NULL,
  time TEXT NOT NULL,
  date TEXT NOT NULL,
  status TEXT NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);
